### ISSUE TITLE
Buffer underflow, even though available() is used to check if there is data

### ISSUE THREAD

**Issue by dedobbin** [Imrekorf/LinSerial#1]
Code example to reproduce the problem:

```
LinSer::Serial port("/dev/ttyACM0", LinSer::SerParam(
    LinSer::SerParam::Baudrate::Baud9600,
    LinSer::SerParam::Parity::PAR_NONE,
    LinSer::SerParam::StopBits::ONE_STOP,
    LinSer::SerParam::BitCount::ByteSize8
), LinSer::SerTimeOut(0, 0));

while (true){
    char buffer[256];
    while (!port.available()){sleep(1);}
    auto n_read = port.readBytesUntil('\n', buffer, 256);
    std::cout << buffer << std::endl;
}
```

I let it run for some minutes, which eventually causes:
    
 ```
Buffer underflow!
terminate called after throwing an instance of 'LinSer::Buffer::SerialBufferUnderflowException'
what():  Buffer undeflow during pop operation
Aborted
```

It also seems to happen on first read when no delay is used, but i haven't looked into that much.

If you need additional info, or if i'm doing something wrong, let me know.

**Comment by Imrekorf** [comment]
Fixed in commit [54ac053](https://github.com/Imrekorf/LinSerial/commit/54ac0537a5a70cb9404ccf4dc7337974372e9565). Was caused by a missing check if length was actually specified
