### ISSUE TITLE
using default /r/n while line ends in /n/r crashes without exception

### ISSUE THREAD

**Issue by thomassocrates** [Imrekorf/LinSerial#2]
while(!port.available()){
                usleep(5000);
            }
            std::cout << std::endl << "Got trigger" << std::endl;
            unsigned long now = std::chrono::system_clock::now().time_since_epoch() / std::chrono::seconds(1);
            std::string data = port.readLine(); //(actual line is: 00000001 /n/r

            std::cout << "Got byte: " << data << std::endl;

code crashes library without exception
![image](https://user-images.githubusercontent.com/85485880/178701461-371a0023-40ce-4f59-aec4-5659b46ba095.png)

**Comment by Imrekorf** [comment]
readline's default terminator string is "\n"
Also does the terminal detail multiple program executions? or is the serial port recreated multiple times causing the serial to close?
Please provide a bigger code snippet that reproduces the problem.

**Comment by dedobbin** [comment]
I played around for a while and i couldn't reproduce this error

Edit: I also accidentally closed the issue hah. Re-opend now.
